config/routes.rb
# frozen_string_literal: true
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  root to: 'welcome#index'
  get :welcome, to: 'welcome#index'

  get 'express', to: 'express#show'
  post 'express', to: 'express#show'

  get 'discover', to: 'discover#index'

  get 'redirect', to: 'redirect#show'

  get 'cgi/search_galileo', to: 'embed#index', as: :embed
  get 'javascript/search_galileo.js', to: 'embed#search_galileo', as: :search_galileo_js
  get 'embed_test', to: 'embed#show'

  # 'home' is an old route but we want to continue to support it with these redirects
  # (see the preferred 'institution_homepage' route below)
  get ':inst_code/home/:view', to: redirect(path: '/%{inst_code}/%{view}')
  get ':inst_code/home',       to: redirect(path: '/%{inst_code}')

  get '(:inst_code)/bento/search', to: 'custom_bento#bento_search', as: 'institution_bento_search'

  get ':inst_code/databases(/:view)', to: 'catalog#index', as: 'institution_databases'
  get ':inst_code/search(/:view)', to: 'catalog#index', as: 'institution_search'
  get ':inst_code/database/:id(/:view)', to: 'catalog#show', as: 'institution_resource'
  get ':inst_code/resource/:id(/:view)', to: 'catalog#show'
  get ':inst_code/embed(/:view)', to: 'homepage#embed', as: 'institution_embed'
  get ':inst_code/sharable_links(/:view)', to: 'homepage#sharable_links', as: 'institution_sharable_links'
  get 'permalink_url_converter', to: 'open_athens_proxy_url_converter#open_athens_proxy_url_converter'
  post 'permalink_url_converter', to: 'open_athens_proxy_url_converter#open_athens_proxy_url_converter'
  get 'open_athens_proxy_url_converter', to: redirect(path: 'permalink_url_converter')

  get ':inst_code/bento/home/:view', to: redirect(path: '/%{inst_code}/%{view}')
  get ':inst_code/bento/home',       to: redirect(path: '/%{inst_code}')
  get ':inst_code/bento/placard(/:view)', to: 'bento#placard_api', as: 'institution_bento_placard'
  get ':inst_code/bento/fulltext', to: 'bento#eds_fulltext', as: 'institution_bento_eds_fulltext'
  get ':inst_code/bento/databases(/:view)', to: 'catalog#bento', as: 'institution_databases_bento'
  get 'bento/links', to: 'bento#alma_links_api', as: 'alma_links_api'
  get 'bento', to: 'bento#index', as: 'bento_search_query'

  get '(:inst_code)/bentos/:bento_type/', to: 'custom_bento#full_results', as: 'bento_full_results'
  match ':inst_code/bentos/:bento_type/api', to: 'custom_bento#full_results_api', via: %i[get post], as: 'bento_full_results_api'
  get ':inst_code/bentos/:bento_type/api/facets/:facet', to: 'custom_bento#facet_api', as: 'bento_facet_api'

  get ':inst_code/bento/api/:bento_type', to: 'custom_bento#bento_api', as: 'institution_bento_api'

  #TODO: will be removed around December release
  get ':inst_code/bento-custom/api/:bento_type', to: 'custom_bento#bento_api', as: 'institution_custom_bento_api'
  get ':inst_code/bento-custom/search', to: 'custom_bento#bento_search', as: 'institution_custom_bento_search'

  # Single record pages
  get ':inst_code/record/eds', to: 'records#eds', as: 'eds_record'
  get ':inst_code/record/journals_ebsco', to: 'records#journals_ebsco', as: 'journals_ebsco_record'

  # wayfinder-related
  post :select, to: 'welcome#select'
  get :clear_remembered, to: 'welcome#clear_remembered'
  post :clear_remembered_selection, to: 'welcome#clear_remembered_selection'
  get :instructions, to: 'welcome#instructions'
  get :wayfinder_data, to: 'wayfinder_data#wayfinder_data'

  get :credentials, to: 'credentials#show'

  scope :auth do
    post :login, to: 'sessions#new'
    get :login, to: 'sessions#new'
    get :logout, to: 'sessions#destroy'
    get :info, to: 'sessions#show'
  end

  post :lti, to: 'lti#create'

  scope :oa do
    get :login, to: 'open_athens#login', as: :oa_login
    get :redirect, to: 'open_athens#redirect', as: :oa_redirect
  end

  get :contact, to: 'contact#index'
  namespace :contact do
    get :dlg
    get :support
    get :other
    get :gkr
    get :nge_revisions
    get :nge_new_article
    get :nge_comments
    get :nge_errors
    post :submit
    post :relay
  end
  post 'cgi/contact', to: 'contact#submit'

  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  get '/link/:code', to: 'link#show', as: 'link'

  resources :view, only: [:index]

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  get '/database/:id', to: 'catalog#show', as: 'resource'

  resources :resources, only: [:show], path: '/resource', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end



  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # these routes need to be at the end
  get ':view', to: 'sessions#new', as: 'view_login', view: /elementary|middle|highschool|educator|full/
  get ':inst_code(/:view)', to: 'homepage#show', as: 'institution_homepage', constraints: { inst_code: /[a-z0-9][a-z0-9][a-z0-9][a-z0-9]/, view: /elementary|middle|highschool|educator|full/ }


  unless Rails.env.production?
    get 'demo/button_options', to: 'demo#button_differentiation_options'
  end
end

app/controllers/homepage_controller.rb
# frozen_string_literal: true

require 'rss'

# :nodoc:
class HomepageController < ApplicationController
  include Blacklight::Searchable
  include GalileoRss
  include ApplicationHelper
  helper FacetHelpers

  content_security_policy false, only: :embed
  before_action :validate_inst_param
  before_action :redirect_to_login, unless: :user
  before_action :validate_inst_matches_user
  before_action :set_solr_institution, unless: @institution
  before_action :validate_view
  before_action :set_features

  after_action :allow_iframe, only: :embed

  layout 'custom_base'

  def show
    set_top_facets
    set_about_content
    @spotlight_link = true
  end

  def bento_home
    set_top_facets
    set_about_content
    @spotlight_link = true
  end

  def embed;
  end

  def sharable_links;
  end

  def glri_tools_link;
  end

  private

  def validate_view
    return unless @view
    unless institution_display_views?(user.inst)
      @view = nil
      cookies.delete(:galileo_search_preferred_view)
      redirect_to institution_homepage_path(inst_code: user.inst.code)
    end
  end

  def validate_inst_matches_user
    return if params[:inst_code] == user.inst.code

    redirect_to institution_homepage_path(inst_code: user.inst.code, view: @view)
  end

  def validate_inst_param
    return unless params.include?(:inst_code)

    vserv = ValidationService.new
    inst_code = params[:inst_code]

    return if vserv.is_active_institution?(inst_code)

    if vserv.is_valid_institution_code?(inst_code)
      flash.alert = 'Institution is not active.'
    else
      # NOTE: this is handled by contraint on '/:inst_code' route, so shouldn't get here
      flash.alert = 'Not understood.'
    end

    redirect_to welcome_path
  end

  def redirect_to_login
    set_solr_institution
    login_path = welcome_path(inst: params[:inst_code], view: params[:view])
    return if warden.authenticate?(:ip)
    if @institution&.open_athens
      redirect_to oa_wayfless_link(@institution, login_path), allow_other_host: true
    else
      redirect_to instructions_path(inst: @institution&.code)
    end
  end

  def set_solr_institution
    @institution = InstitutionService.new.find(params[:inst_code])
  end

  def set_top_facets
    subjects_response = search_service.facet_field_response('subject_sms', 'facet.sort': 'index')
    formats_response = search_service.facet_field_response('format_sms', 'facet.sort': 'index')
    @top_facets = {}
    @top_facets[:subject] = group_counts 'subject_sms', subjects_response['facet_counts']['facet_fields']
    @top_facets[:type] = group_counts 'format_sms', formats_response['facet_counts']['facet_fields']
  end

  # Pull RSS content, but don't wait too long
  def set_about_content
    @about_content = {
      news: grab_news,
      alerts: grab_alerts
    }
  end

  # Blacklight returns facet counts in an unorganized array
  # This groups them into something nicer to work with
  # also, we stop after 4 facets
  # @param [String] field
  # @param [Array] response_fields
  # @return [Array<Hash>] nice array of hashes
  def group_counts(field, response_fields)
    facets = []
    return facets unless response_fields.key? field

    facet_count_array = response_fields[field]
    facet_count_array.each_with_index do |fc, i|
      break if i > 7

      next if i.odd?

      facets << { label: fc, count: facet_count_array[i + 1],
                  href: search_action_path(search_state.add_facet_params(field, fc))}
    end
    facets
  end

  def allow_iframe
    response.headers['X-Frame-Options'] = 'ALLOWALL'
  end

  # region bento_cookie

  def redirect_to_bento_home
    redirect_to institution_bento_home_path(inst_code: user.inst.code)
  end

  def bento_cookie_present?
    cookies[:bento].present?
  end

  def add_bento_cookie
    cookies[:bento] = 'true' if params[:bento_on].present?
  end

  def remove_bento_cookie
    cookies.delete :bento if params[:bento_off].present?
  end

  def set_features
    @features = FeatureService.find_all @institution, @view
  end

  # endregion
end

app/helpers/homepage_helper.rb
# frozen_string_literal: true

# :nodoc:
module HomepageHelper

  # construct url for eds advanced search link
  def discovery_advanced_search_url
    express_path(params: {
                   instcode: user.inst.code, advanced: 1,
                   profile: eds_profile_for(@institution)
                 })
  end

  # get appropriate URL for "Journal List" link
  # typically expect a Primo URL for highered
  # otherwise a EBSCO Fulltext Finder express link (use link for now?)
  # @param [User::Institution] inst
  # @return [String] absolute or relative url
  def url_for_journals(inst)
    val = inst.journals_link
    return val if val =~ /http/

    link_path('zbft')
  end

  # @param [Hash] feature
  # @return [String] absolute or relative url
  def spotlight_image_url(feature)
    feature_image = feature.dig :image

    feature_image_url = @image_service.url_for feature_image

    feature_image_url.blank? ? image_path('spotlight-default.png') : feature_image_url
  end

  def feature_image_url(feature, image_service = @image_service)
    feature_image_url = image_service.url_for feature.image_key

    feature_image_url.blank? ? image_path('spotlight-default.png') : feature_image_url
  end

  # @param [Hash] feature
  # @return [String] relative url
  def spotlight_link_url(feature)
    feature_link = feature.dig(:link).strip

    if feature_link =~ /express.*link=(?<code>#{ValidationService.resource_code_regx})/
      if @institution
        ResourceService.new(@institution.code).find(Regexp.last_match(:code))&.local_express_link
      else
        link_path Regexp.last_match(:code)
      end
    else
      feature_link
    end
  end

  # @return [Bool]
  def elementary_view?
    @view&.to_sym == :elementary
  end

  # @param [User::Institution] inst
  # @return [Array] features
  def institution_view_features(inst)
    inst.features(@view)
  end

  # @param [Array<Feature>] features
  # @return [Array<Feature>]
  def displayed_features(features, feature_count: Feature::FEATURE_COUNT)
    return [] if features.empty?

    inst_features = features.find_all{|feature| feature.institution?}
    inst_group_features = features.find_all{|feature| feature.institution_group?}

    features = (1..feature_count).map do |i|
      inst_feature = inst_features.find{|feature| feature.position == i}
      inst_group_feature = inst_group_features.find{|feature| feature.position == i}
      inst_feature || inst_group_feature
    end
    features.compact
  end


  # @param [String,Symbol] view
  # @return [String] view_type_label
  def view_type_label_new_header(view = @view)
    case view&.to_sym
    when :elementary then '| Elementary School'
    when :middle then '| Middle School'
    when :highschool then '| High School'
    when :educator then '| Educator'
    when :full then '| Full'
    else
      ''
    end
  end

  # @param [String,Symbol] view
  # @return [String] view_type_label
  def view_type_label(view = @view)
    case view&.to_sym
    when :elementary then '- Elementary School'
    when :middle then '- Middle School'
    when :highschool then '- High School'
    when :educator then '- Educator'
    when :full then '- Full'
    else
      ''
    end
  end

  # @param [User::Institution] inst
  # @return [String] eds_profile
  def eds_profile_for(inst)
    DiscoverQueryService.eds_profile_for inst, @view
  end

  # @return [String] css class
  def hero_image_class
    case @view&.to_sym
    when :elementary
      'kids-hero'
    when :middle
      'middle-hero'
    when :highschool
      'hs-hero'
    else
      'default-hero'
    end
  end

  def show_bento_toggle?
    (request.parameters[:controller] == 'homepage' && %w[bento_home show].include?(request.parameters[:action])) ||
      request.parameters[:controller] == 'bento' && request.parameters[:action] == 'bento_search'
  end

  def branding_destination_url
    return root_path unless user

    institution_homepage_path(user.inst.code, view: @view)
  end

  def color_for_kids_spotlight(index)
    index = index % 6
    %w[blue green orange orange blue green][index]
  end

end

app/views/homepage/_about_area.html.erb
<section id="about_inst">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="card-deck">
          <div class="card about-inst-card shadow-sm mb-3">
            <div class="card-body">
              <h3 class="card-title"><%= t('homepage.labels.about_area_about_user', data_interpolation: true, name: user.inst.name.upcase) %></h3>
              <ul class="list-group list-group-flush">
                <% @institution.links.each do |link| %>
                  <li class="list-group-item"><%= link.html_safe %></li>
                <% end %>
              </ul>
            </div>
            <div class="card-body">
              <h3 class="card-title"><%= t('homepage.labels.about_area_tools') %></h3>
              <ul class="list-group list-group-flush mb-3">
                <li class="list-group-item"><a href="<%= institution_embed_path(view: @view) %>"><%= t('homepage.labels.embedding') %></a></li>
                <li class="list-group-item"><a href="<%= institution_sharable_links_path(view: @view) %>"><%= t('homepage.labels.shareable_links') %></a></li>
                <% if open_athens_proxy %>
                <li class="list-group-item"><a href="<%= permalink_url_converter_path %>"><%= t('homepage.labels.open_athens_proxy_url_converter') %></a></li>
                <% end %>

                <% if @institution.glri? %>
                <% path = institution_databases_path(view: @view) %>
                <% path += "?f%5Bglri_b%5D%5B%5D=true" %> <%# TODO: what's the right way to do this? %>
                <li class="list-group-item"><a href="<%= path %>"><%= t('homepage.labels.databases_provided_by', data_interpolation: true,name: user.inst.name) %></a></li>
                <% end %>
                <% zotero_bib_visible = @institution.zotero_bib? %>
                <% if zotero_bib_visible %>
                <li class="list-group-item" data-intro="<%=t('walkthru.homepage.bib_tool_links_zotero_only') %>"><a href="https://about.galileo.usg.edu/support/what_is_zoterobib"><%= t('homepage.labels.zotero_bib') %></a></li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="card about-inst-card galileo-card shadow-sm mb-3">
            <div class="card-body">
              <h3 class="card-title"><%= t('homepage.labels.galileo_news') %></h3>
              <ul class="list-group list-group-flush mb-3">
              <% @about_content[:news]&.each do |entry| %>
                  <% if entry.respond_to? :link %>
                    <li class="list-group-item"><a href="<%= entry.link %>"><%= entry.title %></a></li>
                  <% else %>
                    <li class="list-group-item"><%= entry.title %></li>
                  <% end %>
              <% end %>
              </ul>
              <a href="https://about.galileo.usg.edu/news"><%= t('homepage.labels.view_more_news') %><i class="fas fa-caret-right" aria-hidden="true"></i></a>
            </div>
            <div class="card-body">
              <h3 class="card-title"><%= t('homepage.labels.galileo_system_alerts') %></h3>
              <ul class="list-group list-group-flush mb-3">
                <% @about_content[:alerts]&.each do |entry| %>
                  <% if entry.respond_to? :link %>
                    <li class="list-group-item"><a href="<%= entry.link %>"><%= entry.title %></a></li>
                  <% else %>
                    <li class="list-group-item"><%= entry.title %></li>
                  <% end %>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/homepage/_classic_searchbox.erb
<form action="<%= express_path %>" method="post">
  <div class="home-search-wrapper">
    <div class="row" data-intro="<%= t('walkthru.homepage.discover_search') %>">
      <div class="col-lg-9 col-md-9 col-sm-12 p-0">
        <input id="discovery-search-input"
               name="search_galileo_query"
               type="text" class="search-q q col-form-label-lg home-search-textbox"
               required="required" aria-required="true"
               placeholder="<%= t('homepage.labels.search_galileo') %>"
               value="<%= search_query %>"
        >
      </div>
      <div class="col-lg-3 col-md-3 col-sm-12 p-0">
        <span class="input-group-append">
            <button type="submit"
                    class="btn btn-danger btn-lg home-search-btn search-btn btn-block"
                    id="discovery-search-button">
            <%= t('homepage.labels.search') %>
            </button>
        </span>
      </div>
      <!-- hidden fields -->
      <input type="hidden" name="inst" value="<%= user.inst.code %>">
      <input type="hidden" name="profile" value="<%= eds_profile_for(@institution) %>">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    </div>
  </div>
  <div class="text-right mt-2"><a data-intro="<%= t('walkthru.homepage.advanced_search') %>" href="<%= discovery_advanced_search_url %>">Advanced Search <i class="far fa-arrow-alt-circle-right" aria-hidden="true"></i></a></div>
</form>

app/views/homepage/_eds_search.html.erb
<form action="<%= express_path %>" method="post">
  <div class="home-search-wrapper">
  <div class="row" data-intro="<%= t('walkthru.homepage.discover_search') %>">
    <div class="col-lg-9 col-md-9 col-sm-12 p-0">
        <input id="discovery-search-input"
               name="search_galileo_query"
               type="text" class="search-q q col-form-label-lg home-search-textbox"
               required="required" aria-required="true"
               placeholder="<%= t('homepage.labels.search_galileo') %>"
               value="<%= search_query %>"
        >
    </div>
    <div class="col-lg-3 col-md-3 col-sm-12 p-0">
        <span class="input-group-append">
            <button type="submit"
                    class="btn btn-danger btn-lg home-search-btn search-btn btn-block"
                    id="discovery-search-button">
            <%= t('homepage.labels.search') %>
            </button>
        </span>
    </div>
    <!-- hidden fields -->
    <input type="hidden" name="inst" value="<%= user.inst.code %>">
    <input type="hidden" name="profile" value="<%= eds_profile_for(@institution) %>">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  </div>
</div>
  <div class="text-right mt-2"><a data-intro="<%= t('walkthru.homepage.advanced_search') %>" href="<%= discovery_advanced_search_url %>" class="text-light">Advanced Search <i class="far fa-arrow-alt-circle-right" aria-hidden="true"></i></a></div>
</form>

app/views/homepage/_hero_bento_section.html.erb
<section id="hero" class="bento-hero d-flex align-items-md-center <%= hero_image_class %>">
  <h2 class="sr-only"><%= t('homepage.labels.search_galileo_content') %></h2>
  <div class="container">
    <div class="row">
      <div class="col-12 text-center galileo-tagline">
        <span><%= t('homepage.labels.tagline') %></span>
      </div>
      <div class="col-md-12 col-lg-8 offset-lg-2 eds-search-area">
        <%= render(partial: 'shared/bento_searchbox', locals: {search_query: bento_search_query, full_text: false}) %>
      </div>
      <%= render(partial: 'bento/try_bento_toggle', locals: {on_classic_home: false}) %>
    </div>
  </div>
</section>

app/views/homepage/_hero_section.html.erb
  <% bento_active   = cookies[:classic].present? ? ""        : " active" %>
  <% classic_active = cookies[:classic].present? ? " active" : ""        %>

  <section id="hero" class="new-hero d-flex align-items-md-center <%= hero_image_class %>">
    <h2 class="sr-only"><%= t('homepage.labels.search_galileo_content') %></h2>

    <div class="container">
      <% unless FeatureFlags.enabled? :hide_tagline %>
      <div class="row">
        <div class="col-12 text-center galileo-tagline">
          <span><%= t('homepage.labels.tagline') %></span>
        </div>
      </div>
      <% end %>
      <div class="row mb-3">
        <div class="col-md-12 col-lg-8 offset-lg-2 eds-search-area">
          <div class="search-bg">
          <nav class="nav" id="searchboxTab" role="tablist" aria-owns="sbBentoTab sbClassicTab">
            <a class="nav-link<%= bento_active %>" id="sbBentoTab" role="tab" data-toggle="pill" href="#sbBento" aria-controls="sbBentoTab" aria-selected="true" onclick="gtag('event', 'search_click', { 'event_category' : 'search_type', 'event_label' : 'bento' })">
              <svg aria-hidden="true" viewBox="0 0 20 23">
                <g transform="translate(-1072 -341)">
                  <rect x="1072" y="341" width="6" height="6"></rect>
                  <rect x="1079" y="341" width="6" height="6"></rect>
                  <rect x="1086" y="341" width="6" height="6"></rect>
                  <rect x="1072" y="348" width="6" height="6"></rect>
                  <rect x="1079" y="348" width="6" height="6"></rect>
                  <rect x="1086" y="348" width="6" height="6"></rect>
                  <rect x="1072" width="6" height="6" y="355"></rect>
                  <rect x="1079" width="6" height="6" y="355"></rect>
                  <rect x="1086" width="6" height="6" y="355"></rect>
                </g>
              </svg>
              <%= t('embed.labels.bento_search_tab') %></a>
              <a class="nav-link<%= classic_active %>" id="sbClassicTab" role="tab" data-toggle="pill" href="#sbClassic" aria-controls="sbClassicTab" aria-selected="false" onclick="gtag('event', 'search_click', { 'event_category' : 'search_type', 'event_label' : 'classic' })">
                <svg aria-hidden="true" viewBox="0 0 20 23">
                  <g transform="translate(-654 -332)">
                    <rect x="654" width="9" y="332" height="3"></rect>
                    <rect x="654" width="20" y="338" height="3"></rect>
                    <rect x="654" width="14" y="344" height="3"></rect>
                    <rect x="654" width="20" y="350" height="3"></rect>
                  </g>
                </svg>
                <%= t('embed.labels.search_galileo_tab') %>
              </a>
          </nav>
          <div class="tab-content" id="searchboxTabContent">
            <div class="tab-pane fade show<%= bento_active %>" id="sbBento" role="tabpanel" aria-labelledby="sbBentoTab">
                <%= render partial: 'shared/bento_searchbox', locals: {search_query: params[:bento_search_query], full_text: @full_text} %>
            </div>
            <div class="tab-pane fade show<%= classic_active %>" id="sbClassic" role="tabpanel" aria-labelledby="sbClassicTab">
                <%= render(partial:'classic_searchbox', locals: {search_query: search_query}) %>
            </div>
          </div>
        </div>
      </div>
      </div>
      <div class="row">
        <div class="col text-center">
          <a href="#" class=" new-tour-button btn btn-outline-light in-page-help" role="button" title="<%= t('header.labels.new_tour_button') %>">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 23.648" style="enable-background:new 0 0 122.88 121.08" xml:space="preserve" width="24" height="23.648">
              <path fill="currentColor" d="M3 16.844a.512.512 0 1 1 .629.809L1.045 19.66l-.018 2.705 3.173-.177 1.723-2.74a.512.512 0 0 1 .705-.16.513.513 0 0 1 .16.705l-1.856 2.948a.516.516 0 0 1-.413.252l-3.979.224H.511a.511.511 0 0 1-.508-.513l.025-3.46A.521.521 0 0 1 .227 19l2.776-2.157zm4.831-6.311c1.289-3.853 3.028-6.585 5.473-8.307C15.84.44 19.101-.236 23.375.072a.565.565 0 0 1 .525.552c.413 4.627-.484 7.908-2.397 10.395-1.841 2.391-4.605 4.008-8.035 5.365v4.519a.565.565 0 0 1-.313.507l-3.492 2.157a.565.565 0 0 1-.777-.183.576.576 0 0 1-.08-.223c-.773-5.911-1.595-6.195-6.428-7.865a265.704 265.704 0 0 1-1.624-.565.567.567 0 0 1-.344-.721.588.588 0 0 1 .093-.171l2.303-3.281a.561.561 0 0 1 .488-.24l4.537.215zm9.885-4.353a1.715 1.715 0 0 0-1.219-.504 1.733 1.733 0 0 0-1.219.504 1.715 1.715 0 0 0-.504 1.219c0 .475.195.905.504 1.219a1.715 1.715 0 0 0 1.219.504 1.733 1.733 0 0 0 1.219-.504 1.715 1.715 0 0 0 .504-1.219c0-.476-.195-.905-.504-1.219z"/>
            </svg>
            <%= t('header.labels.new_tour_button')  %>
          </a>
        </div>
      </div>

    </div>
  </section>

app/views/homepage/_resource_search.html.erb
<% unless elementary_view? %>
<div class="home-search-wrapper">
  <%= render_search_bar %>
</div>
<% end %>
<div class="row justify-content-center resource-links">
<% unless elementary_view? %>
  <div class="col-auto">
    <%= link_to t('homepage.labels.all_databases'), institution_databases_path(user.inst.code, view: @view), class: "btn btn-outline-primary btn-sm" %>
  </div>
  <div class="col-auto">
    <%= link_to t('homepage.labels.all_journals'), url_for_journals(@institution), class: 'btn btn-outline-primary btn-sm' %>
  </div>
<% end %>
</div>

app/views/homepage/_sharable_links_general.html.erb
  <!-- sharable_link_general homepage -->
  <div class="card mb-3">
    <div class="card-header">
      <h2 class="h4"><%= t('tools.shareable_links.general.homepage.title') %></h2>
      <div class="m-3">
        <%= t('tools.shareable_links.general.homepage.blurb') %>
      </div>
    </div>
    <div class="card-body">
    <% sharable_links_general_homepage_data.each do |link_data| %>
      <%= render 'sharable_link_modal', sharable_link: link_data %>
    <% end %>
    </div>
  </div>

  <!-- sharable_link_general databases a-z -->
  <div class="card mb-3">
    <div class="card-header">
      <h2 class="h4"><%= t('tools.shareable_links.general.databases.title') %></h2>
      <div class="m-3">
        <%= t('tools.shareable_links.general.databases.blurb') %>
      </div>
    </div>
    <div class="card-body">
    <% sharable_links_general_databases_data.each do |link_data| %>
      <%= render 'sharable_link_modal', sharable_link: link_data %>
    <% end %>
    </div>
  </div>

  <!-- sharable_link_general bento search pages -->
  <div class="card mb-3">
    <div class="card-header">
      <h2 class="h4"><%= t('tools.shareable_links.general.bento_search.title') %></h2>
      <div class="m-3">
        <%= t('tools.shareable_links.general.bento_search.blurb') %>
      </div>
    </div>
    <div class="card-body">
    <% sharable_links_general_bento_search_data.each do |link_data| %>
      <%= render 'sharable_link_bento_modal', sharable_link: link_data %>
    <% end %>
    </div>
  </div>