config/routes.rb
# frozen_string_literal: true
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  root to: 'welcome#index'
  get :welcome, to: 'welcome#index'

  get 'express', to: 'express#show'
  post 'express', to: 'express#show'

  get 'discover', to: 'discover#index'

  get 'redirect', to: 'redirect#show'

  get 'cgi/search_galileo', to: 'embed#index', as: :embed
  get 'javascript/search_galileo.js', to: 'embed#search_galileo', as: :search_galileo_js
  get 'embed_test', to: 'embed#show'

  # 'home' is an old route but we want to continue to support it with these redirects
  # (see the preferred 'institution_homepage' route below)
  get ':inst_code/home/:view', to: redirect(path: '/%{inst_code}/%{view}')
  get ':inst_code/home',       to: redirect(path: '/%{inst_code}')

  get '(:inst_code)/bento/search', to: 'custom_bento#bento_search', as: 'institution_bento_search'

  get ':inst_code/databases(/:view)', to: 'catalog#index', as: 'institution_databases'
  get ':inst_code/search(/:view)', to: 'catalog#index', as: 'institution_search'
  get ':inst_code/database/:id(/:view)', to: 'catalog#show', as: 'institution_resource'
  get ':inst_code/resource/:id(/:view)', to: 'catalog#show'
  get ':inst_code/embed(/:view)', to: 'homepage#embed', as: 'institution_embed'
  get ':inst_code/sharable_links(/:view)', to: 'homepage#sharable_links', as: 'institution_sharable_links'
  get 'permalink_url_converter', to: 'open_athens_proxy_url_converter#open_athens_proxy_url_converter'
  post 'permalink_url_converter', to: 'open_athens_proxy_url_converter#open_athens_proxy_url_converter'
  get 'open_athens_proxy_url_converter', to: redirect(path: 'permalink_url_converter')

  get ':inst_code/bento/home/:view', to: redirect(path: '/%{inst_code}/%{view}')
  get ':inst_code/bento/home',       to: redirect(path: '/%{inst_code}')
  get ':inst_code/bento/placard(/:view)', to: 'bento#placard_api', as: 'institution_bento_placard'
  get ':inst_code/bento/fulltext', to: 'bento#eds_fulltext', as: 'institution_bento_eds_fulltext'
  get ':inst_code/bento/databases(/:view)', to: 'catalog#bento', as: 'institution_databases_bento'
  get 'bento/links', to: 'bento#alma_links_api', as: 'alma_links_api'
  get 'bento', to: 'bento#index', as: 'bento_search_query'

  get '(:inst_code)/bentos/:bento_type/', to: 'custom_bento#full_results', as: 'bento_full_results'
  match ':inst_code/bentos/:bento_type/api', to: 'custom_bento#full_results_api', via: %i[get post], as: 'bento_full_results_api'
  get ':inst_code/bentos/:bento_type/api/facets/:facet', to: 'custom_bento#facet_api', as: 'bento_facet_api'

  get ':inst_code/bento/api/:bento_type', to: 'custom_bento#bento_api', as: 'institution_bento_api'

  #TODO: will be removed around December release
  get ':inst_code/bento-custom/api/:bento_type', to: 'custom_bento#bento_api', as: 'institution_custom_bento_api'
  get ':inst_code/bento-custom/search', to: 'custom_bento#bento_search', as: 'institution_custom_bento_search'

  # Single record pages
  get ':inst_code/record/eds', to: 'records#eds', as: 'eds_record'
  get ':inst_code/record/journals_ebsco', to: 'records#journals_ebsco', as: 'journals_ebsco_record'

  # wayfinder-related
  post :select, to: 'welcome#select'
  get :clear_remembered, to: 'welcome#clear_remembered'
  post :clear_remembered_selection, to: 'welcome#clear_remembered_selection'
  get :instructions, to: 'welcome#instructions'
  get :wayfinder_data, to: 'wayfinder_data#wayfinder_data'

  get :credentials, to: 'credentials#show'

  scope :auth do
    post :login, to: 'sessions#new'
    get :login, to: 'sessions#new'
    get :logout, to: 'sessions#destroy'
    get :info, to: 'sessions#show'
  end

  post :lti, to: 'lti#create'

  scope :oa do
    get :login, to: 'open_athens#login', as: :oa_login
    get :redirect, to: 'open_athens#redirect', as: :oa_redirect
  end

  get :contact, to: 'contact#index'
  namespace :contact do
    get :dlg
    get :support
    get :other
    get :gkr
    get :nge_revisions
    get :nge_new_article
    get :nge_comments
    get :nge_errors
    post :submit
    post :relay
  end
  post 'cgi/contact', to: 'contact#submit'

  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  get '/link/:code', to: 'link#show', as: 'link'

  resources :view, only: [:index]

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  get '/database/:id', to: 'catalog#show', as: 'resource'

  resources :resources, only: [:show], path: '/resource', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end



  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # these routes need to be at the end
  get ':view', to: 'sessions#new', as: 'view_login', view: /elementary|middle|highschool|educator|full/
  get ':inst_code(/:view)', to: 'homepage#show', as: 'institution_homepage', constraints: { inst_code: /[a-z0-9][a-z0-9][a-z0-9][a-z0-9]/, view: /elementary|middle|highschool|educator|full/ }


  unless Rails.env.production?
    get 'demo/button_options', to: 'demo#button_differentiation_options'
  end
end

app/views/shared/_a_to_z.html.erb
<div class="row d-none d-md-block">
<div class="col-md-12">
  <ul class="pagination">
    <% %w[All 0-9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z].each do |label| %>
      <%= render partial:'shared/a_to_z_item',
                 locals: {inst_code: inst_code, label: label,
                          query: query, active_letters: active_letters(params),
                          per_page: params[:per_page]}%>
    <% end %>
  </ul>
</div>
</div>

app/views/shared/_a_to_z_item.html.erb
<li class="page-item <%= 'active' if active_letters.include? label %>">
  <%if label == 'All' %>
  <a class="page-link" href="<%= institution_databases_path(inst_code: inst_code, q: query, view: @view, per_page: per_page) %>">
    <%= 'Show All' %>
  </a>
  <% else %>
    <a class="page-link" href="<%= institution_databases_path(inst_code: inst_code, f: { resource_name_first_char_ss: [label]}, q: query, view: @view, per_page: per_page) %>">
      <%= label %>
    </a>
  <% end %>
</li>

app/views/shared/_bento_searchbox.html.erb
<form action="<%= express_path %>" method="post" data-bento-search>
  <div class="home-search-wrapper">
  <div class="row" data-intro="<%= t('walkthru.bento_results.bento_search') %>">
    <div class="col-lg-9 col-md-9 col-sm-12 p-0">
        <input id="discovery-search-input"
               name="bento_search_query"
               type="text" class="search-q q col-form-label-lg home-search-textbox"
               required="required" aria-required="true"
               placeholder="<%= t('bento.label.bento_search.placeholder') %>"
               data-bento-query
               value="<%= search_query %>"
               >
    </div>
    <div class="col-lg-3 col-md-3 col-sm-12 p-0">
        <span class="input-group-append">
            <button type="submit"
                    class="btn btn-danger btn-lg home-search-btn search-btn btn-block"
                    id="discovery-search-button">
            Search
            </button>
        </span>
    </div>
    <!-- hidden fields -->
    <input type="hidden" name="inst" value="<%= user.inst.code %>">
    <input type="hidden" name="view" value="<%= @view %>">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  </div>
</div>
  <div class="row bento-search-options mt-2">
    <div class="col-6">
      <input type="checkbox" id="full_text_cb" name="full_text"
             <%= 'checked' if full_text %>
             <% if controller_name == 'homepage' %>
                data-intro="<%= t('walkthru.bento_search.full_text') %>"
             <% end %>
      >
      <label class="mb-0" for="full_text_cb"> <%= t('bento.label.bento_search.full_text_only') %></label></div>
    <div class="col-6 text-right"><a href="<%= discovery_advanced_search_url %>"
                                     <% if controller_name == 'homepage' %>
                                     data-intro="<%= t('walkthru.bento_search.advanced_search') %>"
                                     <% end %>
    ><%= t('homepage.labels.advanced_search') %> <i class="far fa-arrow-alt-circle-right" aria-hidden="true"></i></a></div>
  </div>
</form>

app/views/shared/_favicon.html.erb
<%#
Added Apple device icon and PNG 16x16 & 32x32 icons used by browsers.
The site.webmanifest file contains 2 sized PNG versions for Android devices.
The favicon_link_tag helper only supports ico so this alternative was necessary
for modern devices
%>

<%= favicon_link_tag "favicon/apple-touch-icon.png", rel: 'apple-touch-icon', type: 'image/png'  %>

<% %w(16 32).each do |size| %>
  <%= favicon_link_tag "favicon/favicon-#{size}x#{size}.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

app/views/shared/_flash_messages.html.erb
<section class="flash_messages">
  <% [:success, :notice, :error, :alert].each do |type| %>
    <%- alert_class = case type
                      when :success then "alert-success"
                      when :notice  then "alert-info"
                      when :alert   then "alert-warning"
                      when :error   then "alert-danger"
                      else "alert-#{type}"
                      end
    -%>
    <% if flash[type] %>
      <% Array(flash[type]).each do |f| %>
        <div class="alert <%= alert_class %> alert-row"><%= f.html_safe %>
          <a class="close" data-dismiss="alert" href="#">&times;</a>
        </div>
      <% end %>
    <% end %>
  <% end %>
</section>

app/views/shared/_footer.html.erb
<footer>
  <section class="footer">
    <div class="container">
      <div class="row">
        <div class="col-6 col-md-4 col-lg-3">
          <h2><a target="_blank" href="https://about.galileo.usg.edu/about"><%= t('footer.labels.about_galileo') %></a></h2>
          <h2 class="programs-list"><%= t('footer.labels.programs') %></h2>
          <ul>
            <li><a target="_blank" href="https://www.affordablelearninggeorgia.org/"><%= t('footer.labels.affordable_learning') %></a></li>
            <li><a target="_blank" href="https://dlg.usg.edu/"><%= t('footer.labels.dlg') %></a></li>
            <li><a target="_blank" href="https://gil.usg.edu/"><%= t('footer.labels.gil') %></a></li>
          </ul>
        </div>
        <div class="col-6 col-md-4 col-lg-3">
          <h2><a target="_blank" href="https://about.galileo.usg.edu/governance/"><%= t('footer.labels.governance') %></a></h2>
          <h2><a target="_blank" href="https://about.galileo.usg.edu/news/"><%= t('footer.labels.community') %></a></h2>
          <h2><a target="_blank" href="https://about.galileo.usg.edu/tools_training"><%= t('footer.labels.tools_training') %></a></h2>
          <h2><a target="_blank" href="https://about.galileo.usg.edu/portal-redesign-info/#release_notes" <% if params['controller'] == 'homepage' %> data-intro="<%= t('walkthru.homepage.release_notes') %>" <% end %>><%= t('footer.labels.release_notes') %></a></h2>
        </div>
        <div class="col-6 col-md-4 col-lg-3">
          <h2><a href="https://about.galileo.usg.edu/support"><%= t('footer.labels.support') %></a></h2>
          <h2><a target="_blank" href="https://about.galileo.usg.edu/about/accessibility"><%= t('footer.labels.accessibility') %></a></h2>
          <h2><a href="<%= contact_path %>"><%= t('footer.labels.contact_us') %></a></h2>
        </div>
        <div class="col-6 col-md-4 col-lg-3">
          <h2><%= t('footer.labels.stay_connected') %></h2>
          <ul class="socialIcons">
            <li><a target="_blank" href="https://www.facebook.com/galileolibrary/"><i class="fab fa-facebook fa-3x" aria-hidden="true" title="Facebook"></i> <span class="sr-only"><%= t('footer.labels.facebook') %></span></a></li>
            <li>
              <a target="_blank" href="https://twitter.com/galileolibrary"
                 onmouseover="document.getElementById('twitter-icon').setAttribute('fill', '#fff');"
                 onmouseout="document.getElementById('twitter-icon').setAttribute('fill', '#e0e0fa');">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="2.7em" height="2.7em" style="vertical-align: top;margin-top: 1px;">
                  <path id="twitter-icon" d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z" fill="#e0e0fa"/>
                </svg>
                <span class="sr-only"><%= t('footer.labels.twitter') %></span>
              </a>
            </li>
            <li><a target="_blank" href="https://www.youtube.com/user/GALILEOScrapbook/featured"><i class="fab fa-youtube fa-3x" aria-hidden="true" title="YouTube"></i> <span class="sr-only"><%= t('footer.labels.youtube') %></span></a></li>
            <li><a target="_blank" href="https://www.linkedin.com/company/galileo-library/"><i class="fab fa-linkedin fa-3x" aria-hidden="true" title="Linkedin"></i> <span class="sr-only"><%= t('footer.labels.linkedin') %></span></a></li>
            <li><a target="_blank" href="http://eepurl.com/cm0iFL"><i class="fas fa-envelope-open-text fa-3x" aria-hidden="true" title="Newsletter"></i> <span class="sr-only"><%= t('footer.labels.newsletter') %></span></a></li>
          </ul>
        </div>
      </div>
      <div class="row align-items-center">
        <div class="col-12 col-md-6 col-lg-9 mb-3 mb-md-0 mx-sm-auto text-sm-center text-md-left">
          <span><%= t('footer.labels.copyright') %> <%= Date.today.year %> &bull; <a target="_blank" href="https://about.galileo.usg.edu"><%= t('footer.labels.galileo') %></a> &bull; <a target="_blank" href="https://about.galileo.usg.edu/governance/policies#privacy_policy_for_galileo_2.1"><%= t('footer.labels.privacy_policy') %></a> &bull; <a target="_blank" href="https://www.usg.edu"><%= t('footer.labels.usg') %></a></span>
        </div>
        <div class="col-12 col-md-6 col-lg-3 text-center">
        <%= image_tag "logo.svg", alt: t('footer.labels.galileo_logo'), :class => "img-fluid" %>
        </div>
      </div>
    </div>
  </section>
</footer>
<% if authenticated? %>
  <div id="view-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= t('footer.labels.choose_view') %></h5>
        </div>
        <div class="modal-body">
          <div class="row row-cols-2 row-cols-md-2 row-cols-lg-4 card-views">
            <div class="col mb-3">
              <div class="card text-center h-100">
                <%= image_tag '20.GAL.Icon_Elementary_v4.png', class: "card-img-top", alt: "" %>
                <div class="card-body d-flex align-items-center justify-content-center">
                  <h5 class="card-title"><%= link_to t('view.labels.elementary'), request.params.merge(view: 'elementary'), class: 'stretched-link' %></h5>
                </div>
              </div>
            </div>
            <div class="col mb-3">
              <div class="card text-center h-100">
                <%= image_tag '20.GAL.Icon_Middle_v4.png', class: "card-img-top", alt: "" %>
                <div class="card-body d-flex align-items-center justify-content-center">
                  <h5 class="card-title"><%= link_to t('view.labels.middle'), request.params.merge(view: 'middle'), class: 'stretched-link' %></h5>
                </div>
              </div>
            </div>
            <div class="col mb-3">
              <div class="card text-center h-100">
                <%= image_tag '20.GAL.Icon_HS_v4.png', class: "card-img-top", alt: "" %>
                <div class="card-body d-flex align-items-center justify-content-center">
                  <h5 class="card-title"><%= link_to t('view.labels.highschool'), request.params.merge(view: 'highschool'), class: 'stretched-link' %></h5>
                </div>
              </div>
            </div>
            <div class="col mb-3">
              <div class="card text-center h-100">
                <%= image_tag '20.GAL.HERO_Main_v5.png', class: "card-img-top", alt: "" %>
                <div class="card-body d-flex align-items-center justify-content-center">
                  <h5 class="card-title">
                    <% if user.inst.type.to_sym == :k12 %>
                      <%= link_to t('view.labels.educator'), request.params.merge(view: 'educator'), class: 'stretched-link' %>
                    <% else %>
                      <%= link_to t('view.labels.full'), request.params.merge(view: 'full'), class: 'stretched-link' %>
                    <% end %>
                  </h5>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_resource_search_bar.html.erb
<div class="row mb-3">
  <div class="col-md-12 col-lg-8 offset-lg-2 resource-search-area resource-search-blacklight">
    <div class="home-search-wrapper">
    <%= render_search_bar  %>
    </div>
  </div>
</div>