config/routes.rb
# frozen_string_literal: true
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  root to: 'welcome#index'
  get :welcome, to: 'welcome#index'

  get 'express', to: 'express#show'
  post 'express', to: 'express#show'

  get 'discover', to: 'discover#index'

  get 'redirect', to: 'redirect#show'

  get 'cgi/search_galileo', to: 'embed#index', as: :embed
  get 'javascript/search_galileo.js', to: 'embed#search_galileo', as: :search_galileo_js
  get 'embed_test', to: 'embed#show'

  # 'home' is an old route but we want to continue to support it with these redirects
  # (see the preferred 'institution_homepage' route below)
  get ':inst_code/home/:view', to: redirect(path: '/%{inst_code}/%{view}')
  get ':inst_code/home',       to: redirect(path: '/%{inst_code}')

  get '(:inst_code)/bento/search', to: 'custom_bento#bento_search', as: 'institution_bento_search'

  get ':inst_code/databases(/:view)', to: 'catalog#index', as: 'institution_databases'
  get ':inst_code/search(/:view)', to: 'catalog#index', as: 'institution_search'
  get ':inst_code/database/:id(/:view)', to: 'catalog#show', as: 'institution_resource'
  get ':inst_code/resource/:id(/:view)', to: 'catalog#show'
  get ':inst_code/embed(/:view)', to: 'homepage#embed', as: 'institution_embed'
  get ':inst_code/sharable_links(/:view)', to: 'homepage#sharable_links', as: 'institution_sharable_links'
  get 'permalink_url_converter', to: 'open_athens_proxy_url_converter#open_athens_proxy_url_converter'
  post 'permalink_url_converter', to: 'open_athens_proxy_url_converter#open_athens_proxy_url_converter'
  get 'open_athens_proxy_url_converter', to: redirect(path: 'permalink_url_converter')

  get ':inst_code/bento/home/:view', to: redirect(path: '/%{inst_code}/%{view}')
  get ':inst_code/bento/home',       to: redirect(path: '/%{inst_code}')
  get ':inst_code/bento/placard(/:view)', to: 'bento#placard_api', as: 'institution_bento_placard'
  get ':inst_code/bento/fulltext', to: 'bento#eds_fulltext', as: 'institution_bento_eds_fulltext'
  get ':inst_code/bento/databases(/:view)', to: 'catalog#bento', as: 'institution_databases_bento'
  get 'bento/links', to: 'bento#alma_links_api', as: 'alma_links_api'
  get 'bento', to: 'bento#index', as: 'bento_search_query'

  get '(:inst_code)/bentos/:bento_type/', to: 'custom_bento#full_results', as: 'bento_full_results'
  match ':inst_code/bentos/:bento_type/api', to: 'custom_bento#full_results_api', via: %i[get post], as: 'bento_full_results_api'
  get ':inst_code/bentos/:bento_type/api/facets/:facet', to: 'custom_bento#facet_api', as: 'bento_facet_api'

  get ':inst_code/bento/api/:bento_type', to: 'custom_bento#bento_api', as: 'institution_bento_api'

  #TODO: will be removed around December release
  get ':inst_code/bento-custom/api/:bento_type', to: 'custom_bento#bento_api', as: 'institution_custom_bento_api'
  get ':inst_code/bento-custom/search', to: 'custom_bento#bento_search', as: 'institution_custom_bento_search'

  # Single record pages
  get ':inst_code/record/eds', to: 'records#eds', as: 'eds_record'
  get ':inst_code/record/journals_ebsco', to: 'records#journals_ebsco', as: 'journals_ebsco_record'

  # wayfinder-related
  post :select, to: 'welcome#select'
  get :clear_remembered, to: 'welcome#clear_remembered'
  post :clear_remembered_selection, to: 'welcome#clear_remembered_selection'
  get :instructions, to: 'welcome#instructions'
  get :wayfinder_data, to: 'wayfinder_data#wayfinder_data'

  get :credentials, to: 'credentials#show'

  scope :auth do
    post :login, to: 'sessions#new'
    get :login, to: 'sessions#new'
    get :logout, to: 'sessions#destroy'
    get :info, to: 'sessions#show'
  end

  post :lti, to: 'lti#create'

  scope :oa do
    get :login, to: 'open_athens#login', as: :oa_login
    get :redirect, to: 'open_athens#redirect', as: :oa_redirect
  end

  get :contact, to: 'contact#index'
  namespace :contact do
    get :dlg
    get :support
    get :other
    get :gkr
    get :nge_revisions
    get :nge_new_article
    get :nge_comments
    get :nge_errors
    post :submit
    post :relay
  end
  post 'cgi/contact', to: 'contact#submit'

  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  get '/link/:code', to: 'link#show', as: 'link'

  resources :view, only: [:index]

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  get '/database/:id', to: 'catalog#show', as: 'resource'

  resources :resources, only: [:show], path: '/resource', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end



  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # these routes need to be at the end
  get ':view', to: 'sessions#new', as: 'view_login', view: /elementary|middle|highschool|educator|full/
  get ':inst_code(/:view)', to: 'homepage#show', as: 'institution_homepage', constraints: { inst_code: /[a-z0-9][a-z0-9][a-z0-9][a-z0-9]/, view: /elementary|middle|highschool|educator|full/ }


  unless Rails.env.production?
    get 'demo/button_options', to: 'demo#button_differentiation_options'
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

require 'oj'

# :nodoc:
class WelcomeController < ApplicationController
  helper WelcomeHelper
  include ApplicationHelper
  include DiscoverHelper
  include LinkHelper

  before_action :attempt_ip_login, only: :index, if: :from_root_path
  before_action :load_remembered_selections, only: %i[index select clear_remembered_selection]
  before_action :redirect_to_homepage, if: :user
  before_action :set_desired_institution, if: :inst_param?

  after_action :add_to_remembered_cookie, only: :select

  layout 'custom_base'

  def index
    if @institution
      redirect_to instructions_path(inst: @institution.code, dest: params[:dest])
    end
  end

  def select
    institution_service = InstitutionService.new
    @selected = institution_service.find_by_name welcome_params[:wayfinder_selection]
    verify_selected || return # redirect unless @selected is found
    @institution = if @selected.parent
                     institution_service.find @selected.parent
                   else
                     @selected
                   end
    if @institution&.open_athens
      redirect_to oa_wayfless_link(@institution, open_athens_destination), allow_other_host: true
    else
      flash.clear
      redirect_to instructions_path(
        params: { inst: @institution&.code, site: @selected&.code, proxy: params[:proxy],
                  dest: params[:dest], returnData: welcome_params[:returnData] }
      )
    end
  end

  def instructions
    @selected = if welcome_params[:site]
                  InstitutionService.new.find welcome_params[:site]
                else
                  @institution
                end
    if @selected && @institution && ValidationService.new.is_active_institution?(@institution&.code)
      if welcome_params[:dest]
        flash.alert = 'Please enter your password to continue'
      end
      render :instructions
    else
      redirect_to :welcome, alert: "Problem showing instructions"
    end
  end

  def clear_remembered
    cookies.delete :gs_wayf_remembered
    redirect_to :welcome, info: 'Remembered selections cleared.'
  end

  # Remove entry from remember_me cookie
  def clear_remembered_selection
    if @remembered.include?(params[:wayfinder_selection])
      @remembered.delete params[:wayfinder_selection]
      cookies.permanent[:gs_wayf_remembered] = Oj.dump @remembered[0..4]
    end

    redirect_to :welcome
  end

  private

  def open_athens_destination
    if cookies[:galileo_discovery]
      discover_url
    elsif params[:dest]
      params[:dest]
    else
      institution_homepage_url(inst_code: @institution.code)
    end
  end

  # this is a bit oblique, but when used with "verify_selected || return"
  # returns an early redirect from a controller method (redirect_to does not
  # stop method execution)
  def verify_selected
    unless @selected
      redirect_to(:welcome,
                  alert: 'Please select a displayed option in the menu below') &&
        return
    end
    true
  end

  def load_remembered_selections
    @remembered = Oj.load cookies[:gs_wayf_remembered] || '[]'
  end

  # Add selected entry to the remember_me cookie
  def add_to_remembered_cookie
    return if !@selected || @remembered.include?(@selected.name)

    @remembered.prepend @selected.name
    cookies.permanent[:gs_wayf_remembered] = Oj.dump @remembered[0..4]
  end

  # check if request is initiated by visiting root_path
  # @return [TrueClass, FalseClass]
  def from_root_path
    request.fullpath == root_path
  end

  # try IP authentication and fail silently
  # @return [TrueClass, FalseClass]
  def attempt_ip_login
    warden.authenticate?(:ip)
  end

  def inst_param?
    welcome_params.include? :inst
  end

  def redirect_to_homepage
    redirect_to institution_homepage_path(inst_code: user.inst.code, view: welcome_params[:view])
  end

  def set_desired_institution
    @institution = InstitutionService.new.find(welcome_params[:inst])
  end

  def welcome_params
    params.permit(:inst, :wayfinder_selection, :site, :proxy, :dest, :view, :returnData, :authenticity_token, :commit)
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

# :nodoc:
module WelcomeHelper
  def render_institution_type_help(institution_type)
    case institution_type
    when 'highered'
      render 'welcome/help/highered'
    when 'k12'
      render 'welcome/help/k12'
    when 'publiclib'
      render 'welcome/help/publiclib'
    else
      render 'welcome/help/default'
    end
  end

  def instruction_page_title
    @selected.name
  end

  def wayfinder_placeholder(type)
    case type
    when 'k12' then 'Your Georgia School'
    when 'publiclib' then 'Your Georgia Public Library'
    when 'highered' then 'Your Georgia College or University'
    else
      'Enter school or library name.'
    end
  end
end

app/views/welcome/_passphrase_form.html.erb
<%= bootstrap_form_with url: login_path, method: :post, inline: true do |f| %>
        <% if params[:proxy] %>
          <%= f.hidden_field :proxy, value: params['proxy'] %>
        <% end %>
        <% if params[:dest] %>
          <%= f.hidden_field :dest, value: params['dest'] %>
        <% end %>
        <% if params[:inst] %>
          <%= f.hidden_field :inst, value: params['inst'] %>
        <% end %>
        <% if params[:site] %>
          <%= f.hidden_field :site, value: params['site'] %>
        <% end %>
        <% if params[:view] %>
          <%= f.hidden_field :view, value: params['view'] %>
        <% end %>
        <% if params[:returnData] %>
          <%= f.hidden_field :returnData, value: params['returnData'] %>
        <% end %>
        <label class="my-1 mr-2 sr-only" for="passphrase">Your GALILEO password</label>
        <div class="input-group w-100 flex-nowrap">
          <input name="passphrase" type="password"
                 placeholder="<%= passphrase_input_placeholder %>"
                 class="form-control" />
          <div class="input-group-append">
            <%= f.submit t('welcome.labels.go'), class: 'btn btn-primary passphrase-login-button' %>
          </div>
        </div>
        <div class="my-2">
          <p class="text-left font-italic">Password access is no longer available for <%= link_to "some institutions", 'https://about.galileo.usg.edu/support/which_galileo_institutions_no_longer_provide_galileo_password_access' %>. If you are unable to login, please contact your library for assistance.</p>
          <%= link_to t('welcome.labels.having_trouble'), 'https://about.galileo.usg.edu/support' %>
        </div>
      <% end %>

app/views/welcome/_remembered.html.erb
<div class="remembered">
  <div class="d-flex flex-row flex-md-nowrap flex-wrap mt-md-4 mt-2">
    <h3 class="mr-1">
      <%= t('welcome.labels.recent_selections') %>
    </h3>
  <div>
    <div class="login-history">
  <% @remembered.each do |entry| %>
    <div class="badge">
      <div class="d-flex align-items-center">
        <span><%= button_to entry, select_path(wayfinder_selection: entry, proxy: params[:proxy], dest: params[:dest], returnData: params[:returnData]), method: :post, class: ""%></span>
        <%= button_to(clear_remembered_selection_path(wayfinder_selection: entry), method: :post, class: "close pl-1", aria: { label: "Remove" }) do %>
              <i class="fa fa-times" aria-hidden="true"></i>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>
  </div>
  </div>
</div>

app/views/welcome/_wayfinder.html.erb
<ul class="nav nav-pills justify-content-center mb-3" id="wayfinderTab" role="tablist">
  <li class="nav-item"><a class="nav-link active" id="wayfAllTab" role="tab" data-toggle="pill" href="#wayfAll" aria-controls="wayfAll" aria-selected="true"><%= t('welcome.labels.all') %></a></li>
  <li class="nav-item"><a class="nav-link" id="wayfK12Tab" role="tab" data-toggle="pill" href="#wayfK12" aria-controls="wayfK12" aria-selected="false"><%= t('welcome.labels.k12') %></a></li>
  <li class="nav-item"><a class="nav-link" id="wayfPublicLibrariesTab" role="tab" data-toggle="pill" href="#wayfPublicLibraries" aria-controls="wayfPublicLibraries" aria-selected="false"><%= t('welcome.labels.public_libraries') %></a></li>
  <li class="nav-item"><a class="nav-link" id="wayfHigherEdTab" role="tab" data-toggle="pill" href="#wayfHigherEd" aria-controls="wayfHigherEd" aria-selected="false"><%= t('welcome.labels.colleges_and_uni') %></a></li>
</ul>
<div class="tab-content" id="wayfinderTabContent">
  <div class="tab-pane fade show active" id="wayfAll" role="tabpanel" aria-labelledby="wayfAllTab">
    <%= render 'wayfinder_form', type: 'all', label: t('welcome.labels.start_typing_inst'), list_elements: nil %>
  </div>
  <div class="tab-pane fade" id="wayfElementary" role="tabpanel" aria-labelledby="wayfElementaryTab">
    <%= render 'wayfinder_form', type: 'elementary', label: t('welcome.labels.start_typing_elementary'), list_elements: nil %>
  </div>
  <div class="tab-pane fade" id="wayfMiddle" role="tabpanel" aria-labelledby="wayfMiddleTab">
    <%= render 'wayfinder_form', type: 'middle', label: t('welcome.labels.start_typing_middle'), list_elements: nil %>
  </div>
  <div class="tab-pane fade" id="wayfHighSchool" role="tabpanel" aria-labelledby="wayfHighSchoolTab">
    <%= render 'wayfinder_form', type: 'highschool',
               label: t('welcome.labels.start_typing_highschool'),
               list_elements: nil %>
  </div>
  <div class="tab-pane fade" id="wayfOtherK12" role="tabpanel" aria-labelledby="wayfOtherK12Tab">
    <%= render 'wayfinder_form', type: 'otherk12',
               label: t('welcome.labels.start_typing_school'),
               list_elements: nil %>
  </div>
  <div class="tab-pane fade" id="wayfK12sites" role="tabpanel" aria-labelledby="wayfK12SitesTab">
    <%= render 'wayfinder_form', type: 'k12sites',
               label: t('welcome.labels.start_typing_school'),
               list_elements: nil %>
  </div>
  <div class="tab-pane fade" id="wayfK12" role="tabpanel" aria-labelledby="wayfK12Tab">
    <%= render 'wayfinder_form', type: 'k12',
               label: t('welcome.labels.start_typing_school'),
               list_elements: nil %>
  </div>
  <div class="tab-pane fade" id="wayfPublicLibraries" role="tabpanel" aria-labelledby="wayfPublicTab">
    <%= render 'wayfinder_form', type: 'publiclib',
               label: t('welcome.labels.start_typing_library'),
               list_elements: nil %>
  </div>
  <div class="tab-pane fade" id="wayfHigherEd" role="tabpanel" aria-labelledby="wayfHigherEdTab">
    <%= render 'wayfinder_form', type: 'highered',
               label: t('welcome.labels.start_typing_school'),
               list_elements: nil %>
  </div>
</div>
<% if @remembered.any? %>
  <%= render 'remembered' %>
<% else %>
  <a href="#" class="btn btn-link in-page-help mr-3" role="button"><%= t('header.labels.login_help') %></a>
<% end %>

app/views/welcome/_wayfinder_form.html.erb
<%= bootstrap_form_with(url: select_path,
                        method: :post,
                        id: "wayfinder-form-#{type}",
                        class: 'form-inline wayfinder-select-form') do |f| %>
  <% if params[:proxy] %>
    <%= f.hidden_field :proxy, value: params['proxy'] %>
  <% end %>
  <% if params[:dest] %>
    <%= f.hidden_field :dest, value: params['dest'] %>
  <% end %>
  <% if params[:returnData] %>
    <%= f.hidden_field :returnData, value: params['returnData'] %>
  <% end %>

  <label class="my-1 mr-2 sr-only" for="galileo-wayfinder-<%= type %>"><%= label %></label>
  <div class="input-group w-100 flex-nowrap">
    <input name="wayfinder_selection"
           id="galileo-wayfinder-<%= type %>"
           class="typeahead typeahead-<%= type %> form-control form-control-lg"
           placeholder="<%= wayfinder_placeholder(type) %>" />
    <div class="input-group-append">
      <%= f.submit t('welcome.labels.go'), class: 'btn btn-primary wayfinder-submit-button' %>
    </div>
  </div>
  <% if list_elements %>
    <div id="wayfinder-items-<%= type %>" hidden>
      <% list_elements.each do |e| %>
        <option><%= e %></option>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<% content_for :head do %>
  <%# <meta name="turbolinks-visit-control" content="reload"> %>
  <%# <meta name="turbolinks-cache-control" content="no-cache"> %>
  <%= javascript_packs_with_chunks_tag 'wayfinder' %>
<% end %>

  <% content_for(:skip_link) { skip_link_to '#galileo-wayfinder-all', t('welcome.labels.start_here_find') } %>

  <% content_for :header do %>
    <h1 class="sr-only"><%= t('welcome.labels.georgia_virtual_library') %></h1>
    <section id="hero" class="d-flex align-items-md-center welcome <%= hero_image_class %> new-welcome-page">
      <div class="container">
        <div class="row">
          <% unless FeatureFlags.enabled? :hide_tagline %>
            <div class="col-12 text-center galileo-tagline">
              <%= t('welcome.labels.tagline') %>
            </div>
          <% end %>
          <div class="col-md-12 col-lg-8 offset-lg-2 wayfinder">
            <div class="home-search-wrapper">
              <div class="card" data-intro="<%= t('walkthru.welcome.wayfinder') %>" data-position="bottom">
                <div class="card-body">
                  <h2 class="card-title text-center wayfinder-heading">
                    <i class="fa fa-location-arrow" aria-hidden="true"></i>
                    <%= t('welcome.labels.start_here_find') %>
                  </h2>
                  <div class="card-text">
                    <%= render 'wayfinder' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  <% end %>

  <% content_for :welcome do %>
<div id="welcome_page">
  <section id="welcome" class="new-welcome-page">
    <div id="steps">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>Steps to Access GALILEO</h2>
            <p class="steps-tagline">GALILEO is free to all Georgians via schools, colleges and public libraries.</p>
            <div class="card-deck">
              <div class="card focused">
                <div class="circle-icon">
                  <i class="fa fa-location-arrow fa-2x" aria-hidden="true"></i>
                </div>
                <div class="card-body">
                  <h3 class="card-title">Step 1</h3>
                  <p class="card-text">Find your school, university, or local library in the dropdown list and click "Go".</p>
                </div>
              </div>
              <div class="card">
                <div class="circle-icon">
                  <i class="fa fa-lock fa-2x" aria-hidden="true"></i>
                </div>
                <div class="card-body">
                  <h3 class="card-title">Step 2</h3>
                  <p class="card-text">Log in. If you don't know your account/password, ask your librarian. (If you need a public library account, <a target="_blank" href="https://gapines.org/eg/opac/register">get one here</a>.)</p>
                </div>
              </div>
              <div class="card">
                <div class="circle-icon">
                  <i class="fa fa-search fa-2x" aria-hidden="true"></i>
                </div>
                <div class="card-body">
                  <h3 class="card-title">Step 3</h3>
                  <p class="card-text">Start searching! A universe of resources - including databases, journals, ebooks, videos, and more - is freely available in GALILEO Search.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row justify-content-center mt-5">
          <div class="col-md-8 col-lg-5" data-intro="<%= t('walkthru.welcome.password') %>" data-position="top">
            <div class="accordion" id="passwordAccordion">
              <div class="card">
                <div id="headingOne">
                  <h4 class="mb-0">
                    <button class="btn btn-link btn-block text-center" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                      <i class="fa fa-1x fa-chevron-circle-up" aria-hidden="true"></i>
                      <i class="fa fa-chevron-circle-down" aria-hidden="true"></i>
                      <% if @institution %>
                        <%= t('welcome.labels.the_password') %>
                      <% else %>
                        <%= t('welcome.labels.your_password') %>
                      <% end %>
                    </button>
                  </h4>
                </div>
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#passwordAccordion">
                  <div class="card-body">
                    <%= render 'passphrase_form' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
  <% end %>

app/views/welcome/instructions.html.erb
  <div class="container">
    <div class="instructions_page_login">
    <div class="row">
      <div class="col-12">
        <h1 class="sr-only"><%= t('welcome.labels.login_instructions_page') %></h1>
        <div class="circle-icon">
          <i class="fa fa-lock" aria-hidden="true"></i>
        </div>
        <h2 class="text-center mt-5">
          <%= instruction_page_title %>
        </h2>
        <div class="row mt-3">
          <div class="col-md-12 col-lg-8 offset-lg-2">
            <%= render 'passphrase_form' %>
            <div class="accordion mt-5" id="passwordAccordion">
              <div class="card">
                <div id="headingOne">
                  <h4 class="mb-0">
                    <button class="btn btn-link btn-block text-center" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                      <i class="fa fa-1x fa-chevron-circle-up" aria-hidden="true"></i>
                      <i class="fa fa-chevron-circle-down" aria-hidden="true"></i>
                      <%= t('welcome.labels.need_a_pass')  %>
                    </button>
                  </h4>
                </div>
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#passwordAccordion">
                  <div class="card-body">
                    <%= render_institution_type_help(@institution.type) %>
                    <a href="https://about.galileo.usg.edu/support/category/passwords" target="_blank" class="btn btn-primary"><%= t('welcome.labels.password_faqs') %></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>

  <div id="steps" class="mt-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Steps to Access GALILEO</h2>
          <p class="steps-tagline">GALILEO is free to all Georgians via schools, colleges and public libraries.</p>
          <div class="card-deck">
            <div class="card">
              <div class="circle-icon">
                <i class="fa fa-location-arrow fa-2x" aria-hidden="true"></i>
              </div>
              <div class="card-body">
                <h3 class="card-title">Step 1</h3>
                <p class="card-text">Find your school, university, or local library in the dropdown list and click "Go".</p>
              </div>
            </div>
            <div class="card focused">
              <div class="circle-icon">
                <i class="fa fa-lock fa-2x" aria-hidden="true"></i>
              </div>
              <div class="card-body">
                <h3 class="card-title">Step 2</h3>
                <p class="card-text">
                  Log in. If you don't know your account/password, ask your librarian. (If you need a public library account, <a target="_blank" href="https://gapines.org/eg/opac/register">get one here</a>.)
                </p>
              </div>
            </div>
            <div class="card">
              <div class="circle-icon">
                <i class="fa fa-search fa-2x" aria-hidden="true"></i>
              </div>
              <div class="card-body">
                <h3 class="card-title">Step 3</h3>
                <p class="card-text">Start searching! A universe of resources - including databases, journals, ebooks, videos, and more - is freely available in GALILEO Search.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>