config/routes.rb
# frozen_string_literal: true
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  root to: 'welcome#index'
  get :welcome, to: 'welcome#index'

  get 'express', to: 'express#show'
  post 'express', to: 'express#show'

  get 'discover', to: 'discover#index'

  get 'redirect', to: 'redirect#show'

  get 'cgi/search_galileo', to: 'embed#index', as: :embed
  get 'javascript/search_galileo.js', to: 'embed#search_galileo', as: :search_galileo_js
  get 'embed_test', to: 'embed#show'

  # 'home' is an old route but we want to continue to support it with these redirects
  # (see the preferred 'institution_homepage' route below)
  get ':inst_code/home/:view', to: redirect(path: '/%{inst_code}/%{view}')
  get ':inst_code/home',       to: redirect(path: '/%{inst_code}')

  get '(:inst_code)/bento/search', to: 'custom_bento#bento_search', as: 'institution_bento_search'

  get ':inst_code/databases(/:view)', to: 'catalog#index', as: 'institution_databases'
  get ':inst_code/search(/:view)', to: 'catalog#index', as: 'institution_search'
  get ':inst_code/database/:id(/:view)', to: 'catalog#show', as: 'institution_resource'
  get ':inst_code/resource/:id(/:view)', to: 'catalog#show'
  get ':inst_code/embed(/:view)', to: 'homepage#embed', as: 'institution_embed'
  get ':inst_code/sharable_links(/:view)', to: 'homepage#sharable_links', as: 'institution_sharable_links'
  get 'permalink_url_converter', to: 'open_athens_proxy_url_converter#open_athens_proxy_url_converter'
  post 'permalink_url_converter', to: 'open_athens_proxy_url_converter#open_athens_proxy_url_converter'
  get 'open_athens_proxy_url_converter', to: redirect(path: 'permalink_url_converter')

  get ':inst_code/bento/home/:view', to: redirect(path: '/%{inst_code}/%{view}')
  get ':inst_code/bento/home',       to: redirect(path: '/%{inst_code}')
  get ':inst_code/bento/placard(/:view)', to: 'bento#placard_api', as: 'institution_bento_placard'
  get ':inst_code/bento/fulltext', to: 'bento#eds_fulltext', as: 'institution_bento_eds_fulltext'
  get ':inst_code/bento/databases(/:view)', to: 'catalog#bento', as: 'institution_databases_bento'
  get 'bento/links', to: 'bento#alma_links_api', as: 'alma_links_api'
  get 'bento', to: 'bento#index', as: 'bento_search_query'

  get '(:inst_code)/bentos/:bento_type/', to: 'custom_bento#full_results', as: 'bento_full_results'
  match ':inst_code/bentos/:bento_type/api', to: 'custom_bento#full_results_api', via: %i[get post], as: 'bento_full_results_api'
  get ':inst_code/bentos/:bento_type/api/facets/:facet', to: 'custom_bento#facet_api', as: 'bento_facet_api'

  get ':inst_code/bento/api/:bento_type', to: 'custom_bento#bento_api', as: 'institution_bento_api'

  #TODO: will be removed around December release
  get ':inst_code/bento-custom/api/:bento_type', to: 'custom_bento#bento_api', as: 'institution_custom_bento_api'
  get ':inst_code/bento-custom/search', to: 'custom_bento#bento_search', as: 'institution_custom_bento_search'

  # Single record pages
  get ':inst_code/record/eds', to: 'records#eds', as: 'eds_record'
  get ':inst_code/record/journals_ebsco', to: 'records#journals_ebsco', as: 'journals_ebsco_record'

  # wayfinder-related
  post :select, to: 'welcome#select'
  get :clear_remembered, to: 'welcome#clear_remembered'
  post :clear_remembered_selection, to: 'welcome#clear_remembered_selection'
  get :instructions, to: 'welcome#instructions'
  get :wayfinder_data, to: 'wayfinder_data#wayfinder_data'

  get :credentials, to: 'credentials#show'

  scope :auth do
    post :login, to: 'sessions#new'
    get :login, to: 'sessions#new'
    get :logout, to: 'sessions#destroy'
    get :info, to: 'sessions#show'
  end

  post :lti, to: 'lti#create'

  scope :oa do
    get :login, to: 'open_athens#login', as: :oa_login
    get :redirect, to: 'open_athens#redirect', as: :oa_redirect
  end

  get :contact, to: 'contact#index'
  namespace :contact do
    get :dlg
    get :support
    get :other
    get :gkr
    get :nge_revisions
    get :nge_new_article
    get :nge_comments
    get :nge_errors
    post :submit
    post :relay
  end
  post 'cgi/contact', to: 'contact#submit'

  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  get '/link/:code', to: 'link#show', as: 'link'

  resources :view, only: [:index]

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  get '/database/:id', to: 'catalog#show', as: 'resource'

  resources :resources, only: [:show], path: '/resource', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end



  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # these routes need to be at the end
  get ':view', to: 'sessions#new', as: 'view_login', view: /elementary|middle|highschool|educator|full/
  get ':inst_code(/:view)', to: 'homepage#show', as: 'institution_homepage', constraints: { inst_code: /[a-z0-9][a-z0-9][a-z0-9][a-z0-9]/, view: /elementary|middle|highschool|educator|full/ }


  unless Rails.env.production?
    get 'demo/button_options', to: 'demo#button_differentiation_options'
  end
end

app/controllers/contact_controller.rb
# frozen_string_literal: true

# Contact/Support actions
class ContactController < ApplicationController
  include GalileoRss

  protect_from_forgery :except => [:gkr, :nge_revisions, :nge_new_article, :nge_comments, :nge_errors, :dlg ]

  # show contact us page options, etc.
  def index; end

  # render main "Contact Us" form
  def support; end

  # render "Other" contact form
  def other; end

  # render "DLG" contact form
  def dlg; end

  # render "GKR" contact form
  def gkr; end

  # render "NGE" contact form
  def nge_revisions; end

  # render "NGE" contact form
  def nge_new_article; end

  # render "NGE" contact form
  def nge_comments; end

  # render "NGE" contact form
  def nge_errors; end

  # handle form submissions - form actions should point here
  def submit
    if authenticated? || verify_recaptcha
      form_params = contact_params.merge(user_params)
      mailer = select_mailer(contact_params[:formtype], form_params)
      mailer.deliver_now
      render :thank_you, locals: { formtype: contact_params['formtype'], from_url: contact_params['from_url'] }
    else
      render :recaptcha_fail
    end
  end

  private

  # include form field names here
  def contact_params
    params.permit(:formtype, :institution, :name, :phone, :email, :address,
                  :subject, :resource, :description, :error, :nge_error, :from_url,
                  :attachment1, :attachment2, :attachment3, :recaptcha,
                  :firstname, :lastname, :casetype, :comment, :item,
                  :article_title, :source, :suggested_topic, :page, :nge_page,
                  :correction, :suggestion)
  end

  def select_mailer(form_type, form_params)
    case form_type
    when 'support'
      ContactMailer.support(form_params)
    when 'other'
      ContactMailer.other(form_params)
    when 'dlg'
      ContactMailer.dlg(form_params)
    when 'crdl'
      ContactMailer.dlg(form_params)
    when 'ghnp'
      ContactMailer.dlg(form_params)
    when 'gkr'
      ContactMailer.gkr(form_params)
    when 'rev'
      ContactMailer.nge_revisions(form_params)
    when 'new' # nge_new-article-topics
      ContactMailer.nge_new_article(form_params)
    when 'com' # nge_suggestions-and-comments
      ContactMailer.nge_comments(form_params)
    when 'err' # nge_technical-errors-and-problems
      ContactMailer.nge_errors(form_params)
    else
      nil
    end
  end

  def user_params
    params = {
      ticket_type: parse_ticket_type,
      configuration_item: parse_configuration_item,
      browser: request.user_agent,
      ip: request.remote_ip,
      ezproxy: cookies['ezproxy'] ? 'logged in' : 'not logged in',
      session_id: request.session_options[:id],
      site: parse_site,
      site_code: parse_site_code
    }

    if authenticated?
      params[:remote] = user.remote ? 'remote' : 'on campus'
      params[:auth_type] = user.auth_type
      params[:login_time] =  user.login_time.to_s
      params[:central_ezproxy] = user.inst.proxy
    else
      params[:remote] = 'not logged in'
      params[:auth_type] = 'not logged in'
      params[:login_time] =  'not logged in'
      params[:central_ezproxy] = 'not logged in'
    end

    params
  end

  def parse_ticket_type
    case contact_params[:formtype]
    when 'dlg', 'crdl'
      'DLG'
    when 'ghnp'
      'GHNP'
    when 'com', 'err', 'new', 'rev'
      'NGE'
    when 'gkr'
      'GKR'
    else
      'GALILEO'
    end
  end

  def parse_configuration_item
    formtype = contact_params[:formtype]
    subject  = contact_params[:subject]
    if( %w(dlg crdl).include? formtype  )
      'GALILEO Digital Library of Georgia'
    elsif( formtype&.include?('ghnp') )
      'GALILEO DLG Georgia Historic Newspapers'
    elsif( %w(com err new rev).include? formtype )
      'GALILEO New Georgia Encyclopedia'
    elsif( formtype&.include?('gkr') )
      'GALILEO Georgia Knowledge Repository'
    elsif( subject&.include?('EDS') )
      'GALILEO EBSCO Discovery Service'
    elsif( subject&.include?('OpenAthens') )
      'GALILEO OpenAthens'
    elsif( subject&.include?('GLRI') )
      'GALILEO GLRI'
    elsif( subject&.include?('Alma') )
      'GALILEO Alma'
    else
      'GALILEO'
    end
  end

  def parse_site
    case contact_params[:formtype]
    when 'dlg'
      'Digital Library of Georgia'
    when 'crdl'
      'Civil Rights Digital Library'
    when 'ghnp'
      'Georgia Historic Newspapers'
    when 'com', 'err', 'new', 'rev'
      'New Georgia Encyclopedia'
    when 'gkr'
      'Georgia Knowledge Repository'
    else
      'GALILEO'
    end
  end

  def parse_site_code
    case contact_params[:formtype]
    when 'dlg'
      'DLG'
    when 'crdl'
      'CRDL'
    when 'ghnp'
      'GHNP'
    when 'com', 'err', 'new', 'rev'
      'NGE'
    when 'gkr'
      'GKR'
    else
      'GALILEO'
    end
  end

end

app/helpers/contact_helper.rb
# frozen_string_literal: true

# Helper methods for Contact Form stuff
module ContactHelper
  # @return [Array<Array>]
  def support_form_selections
    [
      [t('contact_forms.labels.support_form_selections.access_issue'), 'Access Issue'],
      [t('contact_forms.labels.support_form_selections.bento_search'), 'Bento Search'],
      [t('contact_forms.labels.support_form_selections.discover_galileo_eds'), 'Discover GALILEO (EDS)'],
      [t('contact_forms.labels.support_form_selections.open_athens'), 'OpenAthens'],
      [t('contact_forms.labels.support_form_selections.glri'), 'GLRI'],
      [t('contact_forms.labels.support_form_selections.alma'), 'Alma'],
      [t('contact_forms.labels.support_form_selections.ip_change'), 'IP Change'],
      [t('contact_forms.labels.support_form_selections.usage_statistics'), 'Usage Statistics'],
      [t('contact_forms.labels.support_form_selections.in_the_spotlight'), 'In the Spotlight'],
      [t('contact_forms.labels.support_form_selections.other'), 'Other']
    ]
  end

  # @return [Array<Array>]
  def other_form_selections
    [
      [t('contact_forms.labels.other_form_selections.marketing'), 'Marketing'],
      [t('contact_forms.labels.other_form_selections.feedback'), 'Feedback'],
      [t('contact_forms.labels.other_form_selections.licensing'), 'Licensing'],
      [t('contact_forms.labels.other_form_selections.training'), 'Training'],
      [t('contact_forms.labels.other_form_selections.content_recommendation'), 'Content Recommendation'],
      [t('contact_forms.labels.other_form_selections.policy'), 'Policy'],
      [t('contact_forms.labels.other_form_selections.other'), 'Other']
    ]
  end

  # @return [Array<Array>]
  def institution_selections
    InstitutionService.new.all_names_with_codes
  end

  # @return [Array<Array>]
  def resource_selections(institution_code)
    ResourceService.new(institution_code).all_names_with_codes
  end

  def service_name(formtype)
    case formtype
    when 'support', 'other'
      'GALILEO'
    when 'nge'
      'New Georgia Encyclopedia'
    when 'gkr'
      'Georgia Knowledge Repository'
    when 'dlg'
      'Digital Library of Georgia'
    when 'crdl'
      'Civil Rights Digital Library'
    when 'ghnp'
      'Georgia Historic Newspapers'
    else
      'GALILEO'
    end
  end

  def legacy_login_status( auth_type, remote )
    case auth_type.to_s
    when 'ip'
      ' (login.via.ip)'
    when 'passphrase'
      ' (login.via.password)'
    when 'geo'
      ' (login.via.ip2loc)'
    when 'pines'
      ' (login.via.pines)'
    when 'oa'
      " (login.via.openathensid_#{remote ? 'remote' : 'ip'})"
    when 'lti'  # TODO: GIL login
      " (login.via.d2lid_#{remote ? 'remote' : 'ip'})"
    else
      ''
    end
  end

  def valid_mime_types
    %w[
      image/png image/gif image/jpeg
      application/msword application/pdf text/plain
      application/vnd.openxmlformats-officedocument.wordprocessingml.document
      application/vnd.ms-excel text/csv
      application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      application/zip
    ].join(',')
  end

end

app/views/contact/dlg.html.erb
<div class="container_fluid p-3">
  <h2>Digital Library of Georgia Contact Form</h2>
  <%= bootstrap_form_tag(url: contact_submit_path, method: :post) do |f| %>
    <%= f.alert_message t('contact_forms.labels.alert_message') %>
    <div class="row">
      <div class="col">
        <%= f.text_field "name",
                         label: t('contact_forms.labels.name'),
                         help: t('contact_forms.help.name'),
                         required: true %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= f.telephone_field "phone",
                              label: t('contact_forms.labels.phone_number'),
                              help: t('contact_forms.help.phone_number') %>
      </div>
      <div class="col">
        <%= f.email_field "email",
                          label: t('contact_forms.labels.email'),
                          help: t('contact_forms.help.email'),
                          required: true %>
      </div>
    </div>

    <%= f.select "casetype", options_for_select(
      [[t('contact_forms.options.gkr.casetype.issue'), 'Issue'],
       [t('contact_forms.options.gkr.casetype.request'), 'Request'],
       [t('contact_forms.options.gkr.casetype.question'), 'Question']], 1),
      { label: t('contact_forms.labels.casetype'),
        help: t('contact_forms.help.casetype') },
      { include_blank: true, required: true } %>
    <%= f.text_area "description",
                    label: t('contact_forms.labels.description'),
                    help: t('contact_forms.help.description'),
                    rows: 8,
                    required: true %>
    <%= f.hidden_field "item", value: "Digital Library of Georgia" %> <!-- TODO: Do we still need?-->
    <%= f.hidden_field :formtype, value: 'dlg'  %>
    <%= f.hidden_field :from_url, value: request.referer %>
    <%= f.select "formtype", options_for_select(
      [['dlg','dlg'],
       ['ghnp','ghnp'],
       ['crdl','crdl']], 1),
      { label: t('contact_forms.labels.formtype'),
        help: t('contact_forms.help.formtype') },
      { include_blank: true, required: true } %>
    <%= recaptcha_tags %>
    <%= f.submit t('contact_forms.labels.submit') %>
  <% end %>
</div>

app/views/contact/gkr.html.erb
<div class="container_fluid p-3">
  <h2><%= t('contact_forms.labels.gkr_contact_heading') %></h2>
  <%= bootstrap_form_tag(url: contact_submit_path, method: :post) do |f| %>
    <%= f.alert_message t('contact_forms.labels.alert_message') %>
    <%= f.text_field "firstname",
                     label: t('contact_forms.labels.first_name'),
                     help: t('contact_forms.help.first_name'),
                     required: true %>
    <%= f.text_field "lastname",
                     label: t('contact_forms.labels.last_name'),
                     help: t('contact_forms.help.last_name'),
                     required: true %>
    <div class="row">
      <div class="col">
        <%= f.telephone_field "phone",
                              label: t('contact_forms.labels.phone_number'),
                              help: t('contact_forms.help.phone_number') %>
      </div>
      <div class="col">
        <%= f.email_field "email",
                          label: t('contact_forms.labels.email'),
                          help: t('contact_forms.help.email'),
                          required: true %>
      </div>
    </div>
    <%= f.select "description", options_for_select(
                 [
                   [t('contact_forms.options.gkr.description.option_1'),"I would like to contribute content to the GKR"],
                   [t('contact_forms.options.gkr.description.option_2'),"My institution would like to join the GKR"],
                   [t('contact_forms.options.gkr.description.option_3'),"My institution is a current member of the GKR"],
                   [t('contact_forms.options.gkr.description.none'),"None of the above"]
                 ], 1),
                 { label: t('contact_forms.labels.description_select') },
                 { include_blank: true, required: true } %>
    <%= f.select "casetype", options_for_select(
                 [
                   [t('contact_forms.options.gkr.casetype.issue'), "Question"],
                   [t('contact_forms.options.gkr.casetype.request'), "Request"],
                   [t('contact_forms.options.gkr.casetype.question'), "Issue"]
                 ], 1),
                 { label: t('contact_forms.labels.casetype') },
                 { include_blank: true, required: true } %>
    <%= f.text_area "comment",
                    label: t('contact_forms.labels.comment_text_area'),
                    help: t('contact_forms.help.comment'),
                    required: true %>

    <%= f.hidden_field "item", value: "Georgia Knowledge Repository" %>
    <%= f.hidden_field :formtype, value: 'gkr'  %>
    <%= recaptcha_tags %>
    <%= f.submit t('contact_forms.labels.submit') %>
  <% end %>
</div>

app/views/contact/index.html.erb
<div class="container">
  <h1 class="py-3"><%= t('contact.labels.contact_galileo') %></h1>
  <div class="row">
    <div class="col-sm-6 pb-5">
      <div class="card text-center">
        <div class="card-header">
          <%= t('contact.labels.technical_card_header') %>
  		</div>
        <div class="card-body">
          <p class="card-text">
            <h5><%= t('contact.labels.support_header') %></h5>
          <%= t('contact.labels.technical_card_text') %>
          </p>
          <a href="<%= contact_support_path %>" class="btn btn-danger stretched-link"><%= t('contact.labels.contact_support_services') %></a>
        </div>
      </div>
    </div>
    <div class="col-sm-6 pb-5">
      <div class="card text-center">
        <div class="card-header">
          <%= t('contact.labels.for_other_card_header') %>
  		</div>
        <div class="card-body">
          <p class="card-text">
            <h5><%= t('contact.labels.general_questions_header') %></h5>
          <%= t('contact.labels.for_other_card_text') %>
          </p>
          <a href="<%= contact_other_path %>" class="btn btn-danger stretched-link"><%= t('contact.labels.contact_support_services') %></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contact/nge_comments.html.erb
<div class="container_fluid p-3">
  <h2><%= t('contact.labels.nge_suggestions_form_heading') %></h2>
  <%= bootstrap_form_tag(url: contact_submit_path, method: :post) do |f| %>
    <%= f.alert_message t('contact_forms.labels.alert_message') %>
    <%= f.text_field "suggestion", label: t('contact_forms.labels.suggestion') %>
    <%= f.text_field "firstname", label: t('contact_forms.labels.first_name')%>
    <%= f.text_field "lastname", label: t('contact_forms.labels.last_name') %>
    <%= f.text_area "address", label: t('contact_forms.labels.address') %>
    <%= f.telephone_field "phone", label: t('contact_forms.labels.phone_number') %>
    <%= f.email_field "email", label: t('contact_forms.labels.email') %>
    <%= f.hidden_field "item", value: "New Georgia Encyclopedia" %>
    <%= f.hidden_field :from_url, value: request.referer %>
    <%= f.hidden_field :formtype, value: 'com'  %>
    <%= recaptcha_tags %>
    <%= f.submit t('contact_forms.labels.submit') %>
  <% end %>
</div>

app/views/contact/nge_errors.html.erb
<div class="container_fluid p-3">
  <h2><%= t('contact.labels.nge_technical_errors_form_heading') %></h2>
  <%= bootstrap_form_tag(url: contact_submit_path, method: :post) do |f| %>
    <%= f.alert_message t('contact_forms.labels.alert_message') %>
    <%= f.text_field "nge_page", label: t('contact_forms.labels.page') %>
    <%= f.text_area "description", label: t('contact_forms.labels.description_of_error') %>
    <%= f.text_field "firstname", label: t('contact_forms.labels.first_name')%>
    <%= f.text_field "lastname", label: t('contact_forms.labels.last_name') %>
    <%= f.text_area "address", label: t('contact_forms.labels.address') %>
    <%= f.telephone_field "phone", label: t('contact_forms.labels.phone_number') %>
    <%= f.email_field "email", label: t('contact_forms.labels.email') %>
    <%= f.hidden_field "item", value: "New Georgia Encyclopedia" %>
    <%= f.hidden_field :from_url, value: request.referer %>
    <%= f.hidden_field :formtype, value: 'err'  %>
    <%= recaptcha_tags %>
    <%= f.submit t('contact_forms.labels.submit') %>
  <% end %>
</div>

app/views/contact/nge_new_article.html.erb
<div class="container_fluid p-3">
  <h2><%= t('contact.labels.new_article_topics') %></h2>
  <%= bootstrap_form_tag(url: contact_submit_path, method: :post) do |f| %>
    <%= f.alert_message t('contact_forms.labels.alert_message') %>
    <%= f.text_field "suggested_topic", label: t('contact_forms.labels.suggested_title') %>
    <%= f.text_area "description", label: t('contact_forms.labels.description_of_new_article') %>
    <%= f.text_area "source", label: t('contact_forms.labels.source') %>
    <%= f.text_field "firstname", label: t('contact_forms.labels.first_name')%>
    <%= f.text_field "lastname", label: t('contact_forms.labels.last_name') %>
    <%= f.text_area "address", label: t('contact_forms.labels.address') %>
    <%= f.telephone_field "phone", label: t('contact_forms.labels.phone_number') %>
    <%= f.email_field "email", label: t('contact_forms.labels.email') %>
    <%= f.hidden_field "item", value: "New Georgia Encyclopedia" %>
    <%= f.hidden_field :from_url, value: request.referer %>
    <%= f.hidden_field :formtype, value: 'new'  %>
    <%= recaptcha_tags %>
    <%= f.submit t('contact_forms.labels.submit') %>
  <% end %>
</div>

app/views/contact/nge_revisions.html.erb
<div class="container_fluid p-3">
  <h2><%= t('contact.labels.nge_revisions_contact_form') %></h2>
  <%= bootstrap_form_tag(url: contact_submit_path, method: :post) do |f| %>
    <%= f.alert_message t('contact_forms.labels.alert_message') %>
    <%= f.text_field "article_title", label: t('contact_forms.labels.article_title') %>
    <%= f.text_area "nge_error", label: t('contact_forms.labels.description_of_error') %>
    <%= f.text_area "correction", label: t('contact_forms.labels.correction') %>
    <%= f.text_area "source", label: t('contact_forms.labels.source') %>
    <%= f.text_field "firstname", label: t('contact_forms.labels.first_name')%>
    <%= f.text_field "lastname", label: t('contact_forms.labels.last_name') %>
    <%= f.text_area "address", label: t('contact_forms.labels.address') %>
    <%= f.telephone_field "phone", label: t('contact_forms.labels.phone_number') %>
    <%= f.email_field "email", label: t('contact_forms.labels.email') %>
    <%= f.hidden_field "item", value: "New Georgia Encyclopedia" %>
    <%= f.hidden_field :from_url, value: request.referer %>
    <%= f.hidden_field :formtype, value: 'rev'  %>
    <%= recaptcha_tags %>
    <%= f.submit t('contact_forms.labels.submit') %>
  <% end %>
</div>

app/views/contact/other.html.erb
<div class="container_fluid p-3">
  <h2>Customer Relations Contact Form</h2>
  <%= bootstrap_form_tag(url: contact_submit_path, method: :post) do |f| %>
    <%= f.alert_message t('contact_forms.labels.alert_message') %>
    <% if authenticated? %>
      <%= f.hidden_field :institution,
                         value: "#{user.inst.name} (#{user.inst.code})" %>
      <p><%= "#{t('contact_forms.labels.institution')}: #{user.inst.name} (#{user.inst.code})" %></p>
    <% else %>
      <%= f.text_field :institution,
                       label: t('contact_forms.labels.institution'),
                       list: 'institutions',
                       help: t('contact_forms.help.institution'),
                       placeholder: t('contact_forms.placeholders.institution_select') %>
      <datalist id="institutions">
        <%= options_for_select institution_selections %>
      </datalist>        <% end %>
      <%= f.text_field :name,
                       label: t('contact_forms.labels.full_name'),
                       help: t('contact_forms.help.full_name'),
                       pattern: ".+ .+",
                       required: true %>
      <div class="row">
        <div class="col">
          <%= f.telephone_field :phone,
                                label: t('contact_forms.labels.phone_number'),
                                help: t('contact_forms.help.phone_number'),
                                required: true %>
        </div>
        <div class="col">
          <%= f.email_field :email,
                            help: t('contact_forms.help.email'),
                            required: true %>
        </div>
      </div>
      <%= f.select :subject, options_for_select(other_form_selections, 1),
                   { label: t('contact_forms.labels.subject') },
                   { include_blank: true, required: true } %>
      <%= f.text_area :description,
                      label: t('contact_forms.labels.description'),
                      help: t('contact_forms.help.description_short'),
                      required: true %>
      <%= f.file_field :attachment1,
                       label: t('contact_forms.labels.attachment'),
                       accept: valid_mime_types,
                       help: t('contact_forms.help.attachment') %>
      <%= f.file_field :attachment2, label: t('contact_forms.labels.attachment'), accept: valid_mime_types %>
      <%= f.file_field :attachment3, label: t('contact_forms.labels.attachment'), accept: valid_mime_types %>

      <%= recaptcha_tags unless authenticated?%>

      <%= f.hidden_field :formtype, value: 'other'  %>
      <%= f.hidden_field :from_url, value: request.referer %>

      <%= f.submit t('contact_forms.labels.submit') %>
    <% end %>
</div>

app/views/contact/thank_you.html.erb
<div class="container-fluid p-3">
  <h1><%= t('contact.labels.contact_galileo') %></h1>
    <h2><%= t('contact.labels.thank_you') %></h2>

  <div class="row">
    <div class="col">
      <p>
        <%= t('contact.labels.confirmation_text.thanks') %><strong><%= service_name(formtype) %></strong>
      </p>
      <p>
        <%= t('contact.labels.confirmation_text.follow_up') %><br />
        <%= t('contact.labels.confirmation_text.business_hours') %>
      </p>
      <p>
        <%= t('contact.labels.confirmation_text.after_hours') %><br />
      <a href="https://about.galileo.usg.edu/site/librarians">
               https://about.galileo.usg.edu/site/librarians</a>
      </p>
      <p>
        <%= t('contact.labels.confirmation_text.troubleshooting') %><br />
      <a href="https://about.galileo.usg.edu/support">
        https://about.galileo.usg.edu/support</a>
      </p>
      <button class="btn btn-primary" onclick="history.go(-2)"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Return</button>
      <%= link_to t('contact.labels.galileo_home_link'), welcome_path, class: 'btn btn-primary'  %>
    </div>
  </div>
</div>